export const LOAD_CLIENT = "LOAD_CLIENT";
export const LOGIN_CLIENT = "LOGIN_CLIENT";
export const FAIL_CLIENT = "FAIL_CLIENT";
export const REGISTER_CLIENT = "REGISTER_CLIENT";
export const LOGOUT_CLIENT = "LOGOUT_CLIENT";
export const CURRENT_CLIENT = "CURRENT_CLIENT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
